all_cities_international = {
    "AAL": "Aalborg, Denmark - (AAL)",
    "AES": "Aalesund, Norway - (AES)",
    "AAR": "Aarhus, Denmark - (AAR)",
    "YXX": "Abbotsford, BC, Canada - (YXX)",
    "ABZ": "Aberdeen, Scotland - (ABZ)",
    "ABR": "Aberdeen, SD, USA - (ABR)",
    "ABJ": "Abidjan, Ivory Coast - (ABJ)",
    "ABI": "Abilene, TX, USA - (ABI)",
    "AUH": "Abu Dhabi, United Arab Emirates - (AUH)",
    "ABV": "Abuja, Nigeria - (ABV)",
    "ACA": "Acapulco, Mexico - (ACA)",
    "ACC": "Accra, Ghana - (ACC)",
    "ADA": "Adana, Turkey - (ADA)",
    "ADD": "Addis Ababa, Ethiopia - (ADD)",
    "ADL": "Adelaide, S.A., Australia - (ADL)",
    "ADE": "Aden, Yemen - (ADE)",
    "ADF": "Adiyaman, Turkey - (ADF)",
    "AGA": "Agadir, Morocco - (AGA)",
    "GUM": "Agana, Guam - (GUM)",
    "BQN": "Aguadilla, Puerto Rico - (BQN)",
    "AGU": "Aguascalientes, Mexico - (AGU)",
    "AHE": "Ahe, French Polynesia - (AHE)",
    "AMD": "Ahmedabad, India - (AMD)",
    "AJA": "Ajaccio, Corsica, France - (AJA)",
    "AXT": "Akita, Japan - (AXT)",
    "CAK": "Akron, OH, USA - (CAK)",
    "ALS": "Alamosa, CO, USA - (ALS)",
    "ABY": "Albany, GA, USA - (ABY)",
    "ALB": "Albany, NY, USA - (ALB)",
    "ALL": "Albenga, Italy - (ALL)",
    "ABQ": "Albuquerque, NM, USA - (ABQ)",
    "ABX": "Albury, N.S.W., Australia - (ABX)",
    "ALY": "Alexandria, Egypt - (ALY)",
    "HBE": "Alexandria, Egypt - (HBE)",
    "AEX": "Alexandria, LA, USA - (AEX)",
    "AXD": "Alexandroupolis, Greece - (AXD)",
    "AHO": "Alghero, Sardinia, Italy - (AHO)",
    "ALG": "Algiers, Algeria - (ALG)",
    "ALC": "Alicante, Spain - (ALC)",
    "ASP": "Alice Springs, N.T., Australia - (ASP)",
    "NSB": "Alice Town, North Bimini Island, Bahamas - (NSB)",
    "ABE": "Allentown, PA, USA - (ABE)",
    "AIA": "Alliance, NE, USA - (AIA)",
    "ALA": "Almaty, Kazakhstan - (ALA)",
    "LEI": "Almeria, Spain - (LEI)",
    "AOR": "Alor Setar, Malaysia - (AOR)",
    "APN": "Alpena, MI, USA - (APN)",
    "ALF": "Alta, Norway - (ALF)",
    "ACH": "Altenrhein, Switzerland - (ACH)",
    "AOO": "Altoona, PA, USA - (AOO)",
    "AMA": "Amarillo, TX, USA - (AMA)",
    "AMM": "Amman, Jordan - (AMM)",
    "AMS": "Amsterdam, Netherlands - (AMS)",
    "YAA": "Anahim Lake, BC, Canada - (YAA)",
    "ANC": "Anchorage, AK, USA - (ANC)",
    "AOI": "Ancona, Italy - (AOI)",
    "ASD": "Andros Town, Bahamas - (ASD)",
    "CRK": "Angeles City, Philippines - (CRK)",
    "TER": "Angra do Heroismo, Terceira Island, Azores - (TER)",
    "ESB": "Ankara, Turkey - (ESB)",
    "AAE": "Annaba, Algeria - (AAE)",
    "NCY": "Annecy, France - (NCY)",
    "AYT": "Antalya, Turkey - (AYT)",
    "TNR": "Antananarivo, Madagascar - (TNR)",
    "ANF": "Antofagasta, Chile - (ANF)",
    "ANR": "Antwerp, Belgium - (ANR)",
    "AOJ": "Aomori, Japan - (AOJ)",
    "AOT": "Aosta, Italy - (AOT)",
    "ATW": "Appleton, WI, USA - (ATW)",
    "ADU": "Ardabil, Iran - (ADU)",
    "AQP": "Arequipa, Peru - (AQP)",
    "EFL": "Argostoli, Kefalonia Island, Greece - (EFL)",
    "ARI": "Arica, Chile - (ARI)",
    "ARH": "Arkhangelsk, Russia - (ARH)",
    "ARM": "Armidale, N.S.W., Australia - (ARM)",
    "ACE": "Arrecife, Lanzarote Island, Canary Islands - (ACE)",
    "ARK": "Arusha, Tanzania - (ARK)",
    "YEK": "Arviat, NWT, Canada - (YEK)",
    "AJR": "Arvidsjaur, Sweden - (AJR)",
    "AVL": "Asheville, NC, USA - (AVL)",
    "ASM": "Asmara, Eritrea - (ASM)",
    "ASE": "Aspen, CO, USA - (ASE)",
    "TSE": "Astana, Kazakhstan - (TSE)",
    "ASU": "Asuncion, Paraguay - (ASU)",
    "ASW": "Aswan, Egypt - (ASW)",
    "ATH": "Athens, Greece - (ATH)",
    "AHN": "Athens, GA, USA - (AHN)",
    "ATL": "Atlanta, GA, USA - (ATL)",
    "ACY": "Atlantic City, NJ, USA - (ACY)",
    "AKL": "Auckland, New Zealand - (AKL)",
    "AGS": "Augusta, GA, USA - (AGS)",
    "AUG": "Augusta, ME, USA - (AUG)",
    "AUS": "Austin, TX, USA - (AUS)",
    "RAR": "Avarua, Rarotonga Island, Cook Islands - (RAR)",
    "AYQ": "Ayers Rock, N.T., Australia - (AYQ)",
    "BCD": "Bacolod, Philippines - (BCD)",
    "BJZ": "Badajoz, Spain - (BJZ)",
    "BGW": "Baghdad, Iraq - (BGW)",
    "YBG": "Bagotville, PQ, Canada - (YBG)",
    "YBC": "Baie-Comeau, PQ, Canada - (YBC)",
    "BFL": "Bakersfield, CA, USA - (BFL)",
    "BAK": "Baku, Azerbaijan - (BAK)",
    "GYD": "Baku, Azerbaijan - (GYD)",
    "SOB": "Balaton, Hungary - (SOB)",
    "TRE": "Balephuil, Scotland - (TRE)",
    "BPN": "Balikpapan, Kalimantan, Indonesia - (BPN)",
    "BNK": "Ballina, N.S.W., Australia - (BNK)",
    "BBA": "Balmaceda, Chile - (BBA)",
    "BWI": "Baltimore, MD, USA - (BWI)",
    "BMV": "Ban Me Thuot, Vietnam - (BMV)",
    "BWN": "Bandar Seri Begawan, Brunei - (BWN)",
    "BLR": "Bangalore, India - (BLR)",
    "BPX": "Bangda, China - (BPX)",
    "BKK": "Bangkok, Thailand - (BKK)",
    "BGR": "Bangor, ME, USA - (BGR)",
    "BGF": "Bangui, Central African Republic - (BGF)",
    "BJL": "Banjul, Gambia - (BJL)",
    "BHB": "Bar Harbor, ME, USA - (BHB)",
    "BCN": "Barcelona, Spain - (BCN)",
    "BDU": "Bardufoss, Norway - (BDU)",
    "BRI": "Bari, Italy - (BRI)",
    "BZL": "Barisal, Bangladesh - (BZL)",
    "BAQ": "Barranquilla, Colombia - (BAQ)",
    "BRW": "Barrow, AK, USA - (BRW)",
    "BSL": "Basel, Switzerland - (BSL)",
    "SKB": "Basseterre, St. Kitts - (SKB)",
    "BIA": "Bastia, Corsica, France - (BIA)",
    "BHS": "Bathurst, N.S.W., Australia - (BHS)",
    "BTR": "Baton Rouge, LA, USA - (BTR)",
    "BAU": "Bauru, Brazil - (BAU)",
    "BPT": "Beaumont, TX, USA - (BPT)",
    "BVA": "Beauvais, France - (BVA)",
    "BKW": "Beckley, WV, USA - (BKW)",
    "BED": "Bedford, MA, USA - (BED)",
    "EIS": "Beef Island, Tortola, British Virgin Islands - (EIS)",
    "BJS": "Beijing, China - (BJS)",
    "BEY": "Beirut, Lebanon - (BEY)",
    "BEL": "Belem, Brazil - (BEL)",
    "BFS": "Belfast, Northern Ireland - (BFS)",
    "BHD": "Belfast, Northern Ireland - (BHD)",
    "BEG": "Belgrade, Serbia and Montenegro - (BEG)",
    "BZE": "Belize City, Belize - (BZE)",
    "BLI": "Bellingham, WA, USA - (BLI)",
    "CNF": "Belo Horizonte, Brazil - (CNF)",
    "BJI": "Bemidji, MN, USA - (BJI)",
    "BEB": "Benbecula, Scotland - (BEB)",
    "BUG": "Benguela, Angola - (BUG)",
    "BGO": "Bergen, Norway - (BGO)",
    "BER": "Berlin, Germany - (BER)",
    "SXF": "Berlin, Germany - (SXF)",
    "THF": "Berlin, Germany - (THF)",
    "TXL": "Berlin, Germany - (TXL)",
    "BRN": "Berne, Switzerland - (BRN)",
    "BET": "Bethel, AK, USA - (BET)",
    "BTT": "Bettles, AK, USA - (BTT)",
    "BIK": "Biak, Papua, Indonesia - (BIK)",
    "BIQ": "Biarritz, France - (BIQ)",
    "BIO": "Bilbao, Spain - (BIO)",
    "BIL": "Billings, MT, USA - (BIL)",
    "BLL": "Billund, Denmark - (BLL)",
    "BGM": "Binghamton, NY, USA - (BGM)",
    "BTU": "Bintulu, Sarawak, Malaysia - (BTU)",
    "BHX": "Birmingham, England - (BHX)",
    "BHM": "Birmingham, AL, USA - (BHM)",
    "FRU": "Bishkek, Kyrgyzstan - (FRU)",
    "BIS": "Bismarck, ND, USA - (BIS)",
    "OXB": "Bissau, Guinea-Bissau - (OXB)",
    "BLZ": "Blantyre, Malawi - (BLZ)",
    "BHE": "Blenheim, New Zealand - (BHE)",
    "BFN": "Bloemfontein, South Africa - (BFN)",
    "BMI": "Bloomington, IL, USA - (BMI)",
    "BMG": "Bloomington, IN, USA - (BMG)",
    "BOO": "Bodo, Norway - (BOO)",
    "BOG": "Bogota, Colombia - (BOG)",
    "BOI": "Boise, ID, USA - (BOI)",
    "BLQ": "Bologna, Italy - (BLQ)",
    "BZO": "Bolzano, Italy - (BZO)",
    "BOD": "Bordeaux, France - (BOD)",
    "BLE": "Borlange, Sweden - (BLE)",
    "BOS": "Boston, MA, USA - (BOS)",
    "BZN": "Bozeman, MT, USA - (BZN)",
    "BSB": "Brasilia, Brazil - (BSB)",
    "BTS": "Bratislava, Slovakia - (BTS)",
    "BZV": "Brazzaville, Congo - (BZV)",
    "BRE": "Bremen, Germany - (BRE)",
    "BES": "Brest, France - (BES)",
    "BGI": "Bridgetown, Barbados - (BGI)",
    "BDS": "Brindisi, Italy - (BDS)",
    "BNE": "Brisbane, Qld., Australia - (BNE)",
    "BRS": "Bristol, England - (BRS)",
    "BHQ": "Broken Hill, N.S.W., Australia - (BHQ)",
    "BKX": "Brookings, SD, USA - (BKX)",
    "BME": "Broome, W.A., Australia - (BME)",
    "BRO": "Brownsville, TX, USA - (BRO)",
    "BQK": "Brunswick, GA, USA - (BQK)",
    "BRU": "Brussels, Belgium - (BRU)",
    "OTP": "Bucharest, Romania - (OTP)",
    "BUD": "Budapest, Hungary - (BUD)",
    "EZE": "Buenos Aires, Argentina - (EZE)",
    "BUF": "Buffalo, NY, USA - (BUF)",
    "BJM": "Bujumbura, Burundi - (BJM)",
    "BUQ": "Bulawayo, Zimbabwe - (BUQ)",
    "BDB": "Bundaberg, Qld., Australia - (BDB)",
    "BUR": "Burbank, CA, USA - (BUR)",
    "BFV": "Buri Ram, Thailand - (BFV)",
    "BRL": "Burlington, IA, USA - (BRL)",
    "BBF": "Burlington, MA, USA - (BBF)",
    "BTV": "Burlington, VT, USA - (BTV)",
    "PUS": "Busan, Korea, Republic of - (PUS)",
    "BTM": "Butte, MT, USA - (BTM)",
    "BXU": "Butuan, Philippines - (BXU)",
    "BZG": "Bydgoszcz, Poland - (BZG)",
    "CFR": "Caen, France - (CFR)",
    "CGY": "Cagayan de Oro, Philippines - (CGY)",
    "CAG": "Cagliari, Sardinia, Italy - (CAG)",
    "CNS": "Cairns, Qld., Australia - (CNS)",
    "CAI": "Cairo, Egypt - (CAI)",
    "CCU": "Calcutta, India - (CCU)",
    "YYC": "Calgary, AB, Canada - (YYC)",
    "CLO": "Cali, Colombia - (CLO)",
    "CLY": "Calvi, Corsica, France - (CLY)",
    "YBL": "Campbell River, BC, Canada - (YBL)",
    "CAL": "Campbeltown, Scotland - (CAL)",
    "CPE": "Campeche, Mexico - (CPE)",
    "CBR": "Canberra, A.C.T., Australia - (CBR)",
    "CUN": "Cancun, Mexico - (CUN)",
    "YGR": "Cap-aux-Meules, Magdalens Islands, PQ, Canada - (YGR)",
    "CGI": "Cape Girardeau, MO, USA - (CGI)",
    "CPT": "Cape Town, South Africa - (CPT)",
    "CCS": "Caracas, Venezuela - (CCS)",
    "CWL": "Cardiff, Wales - (CWL)",
    "CLD": "Carlsbad, CA, USA - (CLD)",
    "CNM": "Carlsbad, NM, USA - (CNM)",
    "CTG": "Cartagena, Colombia - (CTG)",
    "CMN": "Casablanca, Morocco - (CMN)",
    "CPR": "Casper, WY, USA - (CPR)",
    "YCG": "Castlegar, BC, Canada - (YCG)",
    "SLU": "Castries, St. Lucia - (SLU)",
    "CTA": "Catania, Sicily, Italy - (CTA)",
    "CAY": "Cayenne, French Guiana - (CAY)",
    "CYB": "Cayman Brac, Cayman Islands - (CYB)",
    "CEB": "Cebu, Philippines - (CEB)",
    "CID": "Cedar Rapids, IA, USA - (CID)",
    "CED": "Ceduna, S.A., Australia - (CED)",
    "CMI": "Champaign, IL, USA - (CMI)",
    "CGQ": "Changchun, China - (CGQ)",
    "CSX": "Changsha, China - (CSX)",
    "CHQ": "Chania, Crete, Greece - (CHQ)",
    "CHS": "Charleston, SC, USA - (CHS)",
    "CRW": "Charleston, WV, USA - (CRW)",
    "CTL": "Charleville, Qld., Australia - (CTL)",
    "STT": "Charlotte Amalie, St. Thomas, U.S. Virgin Islands - (STT)",
    "CLT": "Charlotte, NC, USA - (CLT)",
    "CHO": "Charlottesville, VA, USA - (CHO)",
    "YYG": "Charlottetown, PEI, Canada - (YYG)",
    "CHA": "Chattanooga, TN, USA - (CHA)",
    "CTU": "Chengdu, China - (CTU)",
    "MAA": "Chennai (Madras), India - (MAA)",
    "CTM": "Chetumal, Mexico - (CTM)",
    "CYS": "Cheyenne, WY, USA - (CYS)",
    "CNX": "Chiang Mai, Thailand - (CNX)",
    "CEI": "Chiang Rai, Thailand - (CEI)",
    "YMT": "Chibougamau, PQ, Canada - (YMT)",
    "CHI": "Chicago, IL, USA - (CHI)",
    "MDW": "Chicago, IL, USA - (MDW)",
    "ORD": "Chicago, IL, USA - (ORD)",
    "CIC": "Chico, CA, USA - (CIC)",
    "CUU": "Chihuahua, Mexico - (CUU)",
    "JKH": "Chios, Greece - (JKH)",
    "KIV": "Chisinau, Moldova - (KIV)",
    "CKG": "Chongqing, China - (CKG)",
    "CHC": "Christchurch, New Zealand - (CHC)",
    "STX": "Christiansted, St. Croix, U.S. Virgin Islands - (STX)",
    "YYQ": "Churchill, MB, Canada - (YYQ)",
    "CVG": "Cincinnati, OH, USA - (CVG)",
    "CBL": "Ciudad Bolivar, Venezuela - (CBL)",
    "CME": "Ciudad Del Carmen, Mexico - (CME)",
    "AGT": "Ciudad del Este, Paraguay - (AGT)",
    "CJS": "Ciudad Juarez, Mexico - (CJS)",
    "CEN": "Ciudad Obregon, Mexico - (CEN)",
    "CVM": "Ciudad Victoria, Mexico - (CVM)",
    "CKB": "Clarksburg, WV, USA - (CKB)",
    "CFE": "Clermont-Ferrand, France - (CFE)",
    "CLE": "Cleveland, OH, USA - (CLE)",
    "CVN": "Clovis, NM, USA - (CVN)",
    "ZSA": "Cockburn Town, San Salvador Island, Bahamas - (ZSA)",
    "COD": "Cody, WY, USA - (COD)",
    "CFS": "Coffs Harbour, N.S.W., Australia - (CFS)",
    "CLQ": "Colima, Mexico - (CLQ)",
    "CLL": "College Station, TX, USA - (CLL)",
    "CGN": "Cologne, Germany - (CGN)",
    "CMB": "Colombo, Sri Lanka - (CMB)",
    "COS": "Colorado Springs, CO, USA - (COS)",
    "COU": "Columbia, MO, USA - (COU)",
    "CAE": "Columbia, SC, USA - (CAE)",
    "CSG": "Columbus, GA, USA - (CSG)",
    "GTR": "Columbus, MS, USA - (GTR)",
    "CMH": "Columbus, OH, USA - (CMH)",
    "CKY": "Conakry, Guinea - (CKY)",
    "CCP": "Concepcion, Chile - (CCP)",
    "NOC": "Connaught, Ireland - (NOC)",
    "CPD": "Coober Pedy, S.A., Australia - (CPD)",
    "CPH": "Copenhagen, Denmark - (CPH)",
    "CPO": "Copiapo, Chile - (CPO)",
    "COR": "Cordoba, Argentina - (COR)",
    "CDV": "Cordova, AK, USA - (CDV)",
    "ORK": "Cork, Ireland - (ORK)",
    "CRP": "Corpus Christi, TX, USA - (CRP)",
    "CBO": "Cotabato, Philippines - (CBO)",
    "CZM": "Cozumel, Mexico - (CZM)",
    "YXC": "Cranbrook, BC, Canada - (YXC)",
    "CRV": "Crotone, Italy - (CRV)",
    "CUL": "Culiacan, Mexico - (CUL)",
    "CWB": "Curitiba, Brazil - (CWB)",
    "CUZ": "Cusco, Peru - (CUZ)",
    "DAD": "Da Nang, Vietnam - (DAD)",
    "DKR": "Dakar, Senegal - (DKR)",
    "DLM": "Dalaman, Turkey - (DLM)",
    "DLU": "Dali City, China - (DLU)",
    "DLC": "Dalian, China - (DLC)",
    "DAL": "Dallas, TX, USA - (DAL)",
    "DFW": "Dallas, TX, USA - (DFW)",
    "DAM": "Damascus, Syria - (DAM)",
    "DGA": "Dangriga, Belize - (DGA)",
    "DAR": "Dar es Salaam, Tanzania - (DAR)",
    "DRW": "Darwin, N.T., Australia - (DRW)",
    "DVO": "Davao, Philippines - (DVO)",
    "DWD": "Dawadmi, Saudi Arabia - (DWD)",
    "DYG": "Dayong, China - (DYG)",
    "DAY": "Dayton, OH, USA - (DAY)",
    "DAB": "Daytona Beach, FL, USA - (DAB)",
    "LGI": "Deadmans Cay, Long Island, Bahamas - (LGI)",
    "DOY": "Deboyne, Papua-New Guinea - (DOY)",
    "DEC": "Decatur, IL, USA - (DEC)",
    "YDF": "Deer Lake, NF, Canada - (YDF)",
    "DEL": "Delhi, India - (DEL)",
    "DPS": "Denpasar, Bali, Indonesia - (DPS)",
    "DEN": "Denver, CO, USA - (DEN)",
    "DSM": "Des Moines, IA, USA - (DSM)",
    "DTW": "Detroit, MI, USA - (DTW)",
    "DVL": "Devils Lake, ND, USA - (DVL)",
    "DPO": "Devonport, Tas., Australia - (DPO)",
    "DAC": "Dhaka, Bangladesh - (DAC)",
    "DIK": "Dickinson, ND, USA - (DIK)",
    "DIN": "Dien-Bien-Phu, Vietnam - (DIN)",
    "DLG": "Dillingham, AK, USA - (DLG)",
    "DPL": "Dipolog, Philippines - (DPL)",
    "JIB": "Djibouti, Djibouti - (JIB)",
    "DNK": "Dnepropetrovsk, Ukraine - (DNK)",
    "DDC": "Dodge City, KS, USA - (DDC)",
    "DOH": "Doha, Qatar - (DOH)",
    "DSA": "Doncaster, England - (DSA)",
    "DOK": "Donetsk, Ukraine - (DOK)",
    "DTM": "Dortmund, Germany - (DTM)",
    "DHN": "Dothan, AL, USA - (DHN)",
    "DLA": "Douala, Cameroon - (DLA)",
    "DRS": "Dresden, Germany - (DRS)",
    "YHD": "Dryden, ON, Canada - (YHD)",
    "DUJ": "Du Bois, PA, USA - (DUJ)",
    "DXB": "Dubai, United Arab Emirates - (DXB)",
    "DBO": "Dubbo, N.S.W., Australia - (DBO)",
    "DUB": "Dublin, Ireland - (DUB)",
    "DBV": "Dubrovnik, Croatia - (DBV)",
    "DBQ": "Dubuque, IA, USA - (DBQ)",
    "DLH": "Duluth, MN, USA - (DLH)",
    "DGT": "Dumaguete, Philippines - (DGT)",
    "DUD": "Dunedin, New Zealand - (DUD)",
    "DGO": "Durango, Mexico - (DGO)",
    "DRO": "Durango, CO, USA - (DRO)",
    "DUR": "Durban, South Africa - (DUR)",
    "DYU": "Dushanbe, Tajikistan - (DYU)",
    "DUS": "Dusseldorf, Germany - (DUS)",
    "DUT": "Dutch Harbor, Un Island, AK, USA - (DUT)",
    "ELS": "East London, South Africa - (ELS)",
    "EMA": "East Midlands, England - (EMA)",
    "EAU": "Eau Claire, WI, USA - (EAU)",
    "EDI": "Edinburgh, Scotland - (EDI)",
    "YEG": "Edmonton, AB, Canada - (YEG)",
    "EEK": "Eek, AK, USA - (EEK)",
    "SVX": "Ekaterinburg, Siberia, Russia - (SVX)",
    "FTE": "El Calafate, Argentina - (FTE)",
    "IPL": "El Centro, CA, USA - (IPL)",
    "ELD": "El Dorado, AR, USA - (ELD)",
    "ELP": "El Paso, TX, USA - (ELP)",
    "ESR": "El Salvador, Chile - (ESR)",
    "EKO": "Elko, NV, USA - (EKO)",
    "ELM": "Elmira, NY, USA - (ELM)",
    "EMD": "Emerald, Qld., Australia - (EMD)",
    "EBB": "Entebbe, Uganda - (EBB)",
    "ERF": "Erfurt, Germany - (ERF)",
    "ERI": "Erie, PA, USA - (ERI)",
    "EBJ": "Esbjerg, Denmark - (EBJ)",
    "ESC": "Escanaba, MI, USA - (ESC)",
    "EUG": "Eugene, OR, USA - (EUG)",
    "ACV": "Eureka, CA, USA - (ACV)",
    "EVV": "Evansville, IN, USA - (EVV)",
    "EVE": "Evenes, Norway - (EVE)",
    "FAI": "Fairbanks, AK, USA - (FAI)",
    "FAR": "Fargo, ND, USA - (FAR)",
    "FMN": "Farmington, NM, USA - (FMN)",
    "FAO": "Faro, Portugal - (FAO)",
    "XNA": "Fayetteville, AR, USA - (XNA)",
    "FAY": "Fayetteville, NC, USA - (FAY)",
    "FEN": "Fernando de Noronha, Brazil - (FEN)",
    "FSC": "Figari, Corsica, France - (FSC)",
    "FLG": "Flagstaff, AZ, USA - (FLG)",
    "YFO": "Flin Flon, MB, Canada - (YFO)",
    "FNT": "Flint, MI, USA - (FNT)",
    "FLR": "Florence, Italy - (FLR)",
    "FLO": "Florence, SC, USA - (FLO)",
    "FRS": "Flores, Guatemala - (FRS)",
    "FOD": "Fort Dodge, IA, USA - (FOD)",
    "FLL": "Fort Lauderdale, FL, USA - (FLL)",
    "TBN": "Fort Leonard Wood, MO, USA - (TBN)",
    "YMM": "Fort McMurray, AB, Canada - (YMM)",
    "RSW": "Fort Myers, FL, USA - (RSW)",
    "YYE": "Fort Nelson, BC, Canada - (YYE)",
    "YXJ": "Fort Saint John, BC, Canada - (YXJ)",
    "FSM": "Fort Smith, AR, USA - (FSM)",
    "YSM": "Fort Smith, NWT, Canada - (YSM)",
    "VPS": "Fort Walton Beach, FL, USA - (VPS)",
    "FWA": "Fort Wayne, IN, USA - (FWA)",
    "FYU": "Fort Yukon, AK, USA - (FYU)",
    "FDF": "Fort-de-France, Martinique - (FDF)",
    "FRA": "Frankfurt, Germany - (FRA)",
    "YFC": "Fredericton, NB, Canada - (YFC)",
    "FPO": "Freeport, Grand Bahama Island, Bahamas - (FPO)",
    "FNA": "Freetown, Sierra Leone - (FNA)",
    "FAT": "Fresno, CA, USA - (FAT)",
    "FDH": "Friedrichshafen, Germany - (FDH)",
    "FUK": "Fukuoka, Japan - (FUK)",
    "FKS": "Fukushima, Japan - (FKS)",
    "FNC": "Funchal, Madeira - (FNC)",
    "FOC": "Fuzhou, China - (FOC)",
    "GNV": "Gainesville, FL, USA - (GNV)",
    "YQX": "Gander, NF, Canada - (YQX)",
    "GCK": "Garden City, KS, USA - (GCK)",
    "YGP": "Gaspe, PQ, Canada - (YGP)",
    "GDN": "Gdansk, Poland - (GDN)",
    "GES": "General Santos, Philippines - (GES)",
    "GVA": "Geneva, Switzerland - (GVA)",
    "GOA": "Genoa, Italy - (GOA)",
    "GGT": "George Town, Great Exuma Island, Bahamas - (GGT)",
    "GEO": "Georgetown, Guyana - (GEO)",
    "GCM": "Georgetown, Grand Cayman Island, Cayman Islands - (GCM)",
    "GCC": "Gillette, WY, USA - (GCC)",
    "GIS": "Gisborne, New Zealand - (GIS)",
    "GLT": "Gladstone, Qld., Australia - (GLT)",
    "GLA": "Glasgow, Scotland - (GLA)",
    "PIK": "Glasgow, Scotland - (PIK)",
    "GDV": "Glendive, MT, USA - (GDV)",
    "OOL": "Gold Coast, Qld., Australia - (OOL)",
    "GOT": "Gothenburg, Sweden - (GOT)",
    "GOV": "Gove, N.T., Australia - (GOV)",
    "GHB": "Governor's Harbour, Eleuthera Island, Bahamas - (GHB)",
    "GRX": "Granada, Spain - (GRX)",
    "GFK": "Grand Forks, ND, USA - (GFK)",
    "GRI": "Grand Island, NE, USA - (GRI)",
    "GJT": "Grand Junction, CO, USA - (GJT)",
    "GRR": "Grand Rapids, MI, USA - (GRR)",
    "YQU": "Grande Prairie, AB, Canada - (YQU)",
    "GRZ": "Graz, Austria - (GRZ)",
    "GTF": "Great Falls, MT, USA - (GTF)",
    "GRB": "Green Bay, WI, USA - (GRB)",
    "LWB": "Greenbrier, WV, USA - (LWB)",
    "GSO": "Greensboro, NC, USA - (GSO)",
    "GLH": "Greenville, MS, USA - (GLH)",
    "PGV": "Greenville, NC, USA - (PGV)",
    "GSP": "Greenville, SC, USA - (GSP)",
    "GFF": "Griffith, N.S.W., Australia - (GFF)",
    "GDL": "Guadalajara, Mexico - (GDL)",
    "CAN": "Guangzhou, China - (CAN)",
    "GUA": "Guatemala City, Guatemala - (GUA)",
    "GYE": "Guayaquil, Ecuador - (GYE)",
    "GYM": "Guaymas, Mexico - (GYM)",
    "GCI": "Guernsey, Channel Islands - (GCI)",
    "KWL": "Guilin, China - (KWL)",
    "GPT": "Gulfport, MS, USA - (GPT)",
    "GUC": "Gunnison, CO, USA - (GUC)",
    "SBH": "Gustavia, St. Barts - (SBH)",
    "HGR": "Hagerstown, MD, USA - (HGR)",
    "HAK": "Haikou, Hainan Island, China - (HAK)",
    "HLD": "Hailar, China - (HLD)",
    "HKD": "Hakodate, Japan - (HKD)",
    "YHZ": "Halifax, NS, Canada - (YHZ)",
    "HAD": "Halmstad, Sweden - (HAD)",
    "HAM": "Hamburg, Germany - (HAM)",
    "BDA": "Hamilton, Bermuda - (BDA)",
    "HLZ": "Hamilton, New Zealand - (HLZ)",
    "HTI": "Hamilton Island, Whitsunday Island, Qld., Australia - (HTI)",
    "YHM": "Hamilton, ON, Canada - (YHM)",
    "HFT": "Hammerfest, Norway - (HFT)",
    "HNM": "Hana, Maui, HI, USA - (HNM)",
    "CMX": "Hancock, MI, USA - (CMX)",
    "IPC": "Hanga Roa, Easter Island, Chile - (IPC)",
    "HGH": "Hangzhou, China - (HGH)",
    "HAJ": "Hannover, Germany - (HAJ)",
    "HAN": "Hanoi, Vietnam - (HAN)",
    "HRE": "Harare, Zimbabwe - (HRE)",
    "HRB": "Harbin, China - (HRB)",
    "HRL": "Harlingen, TX, USA - (HRL)",
    "MDT": "Harrisburg, PA, USA - (MDT)",
    "HRO": "Harrison, AR, USA - (HRO)",
    "BDL": "Hartford, CT, USA - (BDL)",
    "HDY": "Hat Yai, Thailand - (HDY)",
    "HAU": "Haugesund, Norway - (HAU)",
    "HAV": "Havana, Cuba - (HAV)",
    "HVR": "Havre, MT, USA - (HVR)",
    "HYS": "Hays, KS, USA - (HYS)",
    "HFE": "Hefei, China - (HFE)",
    "HLN": "Helena, MT, USA - (HLN)",
    "AGH": "Helsingborg, Sweden - (AGH)",
    "HEL": "Helsinki, Finland - (HEL)",
    "HMV": "Hemavan, Sweden - (HMV)",
    "HER": "Heraklion, Crete, Greece - (HER)",
    "HMO": "Hermosillo, Mexico - (HMO)",
    "HIB": "Hibbing, MN, USA - (HIB)",
    "ITO": "Hilo, Hawaii, USA - (ITO)",
    "HHH": "Hilton Head Island, SC, USA - (HHH)",
    "SGN": "Ho Chi Minh City (Saigon), Vietnam - (SGN)",
    "HBA": "Hobart, Tas., Australia - (HBA)",
    "HOB": "Hobbs, NM, USA - (HOB)",
    "HOQ": "Hof, Germany - (HOQ)",
    "HET": "Hohhot, China - (HET)",
    "HKK": "Hokitika, New Zealand - (HKK)",
    "HOM": "Homer, AK, USA - (HOM)",
    "HKG": "Hong Kong, China - (HKG)",
    "HIR": "Honiara, Guadalcanal, Solomon Islands - (HIR)",
    "HNL": "Honolulu, Oahu, HI, USA - (HNL)",
    "MKK": "Hoolehua, Molokai, HI, USA - (MKK)",
    "HID": "Horn Island, Qld., Australia - (HID)",
    "HOT": "Hot Springs, AR, USA - (HOT)",
    "DJE": "Houmt Souk, Tunisia - (DJE)",
    "EFD": "Houston, TX, USA - (EFD)",
    "HOU": "Houston, TX, USA - (HOU)",
    "IAH": "Houston, TX, USA - (IAH)",
    "HUN": "Hualien, Taiwan - (HUN)",
    "HUI": "Hue, Vietnam - (HUI)",
    "HUY": "Humberside, England - (HUY)",
    "HTS": "Huntington, WV, USA - (HTS)",
    "HSV": "Huntsville, AL, USA - (HSV)",
    "HRG": "Hurghada, Egypt - (HRG)",
    "HON": "Huron, SD, USA - (HON)",
    "HYA": "Hyannis, MA, USA - (HYA)",
    "HYD": "Hyderabad, India - (HYD)",
    "IBA": "Ibadan, Nigeria - (IBA)",
    "IBZ": "Ibiza, Spain - (IBZ)",
    "IDA": "Idaho Falls, ID, USA - (IDA)",
    "JIK": "Ikaria Island, Greece - (JIK)",
    "ILO": "Iloilo, Philippines - (ILO)",
    "IND": "Indianapolis, IN, USA - (IND)",
    "INN": "Innsbruck, Austria - (INN)",
    "INL": "International Falls, MN, USA - (INL)",
    "IVC": "Invercargill, New Zealand - (IVC)",
    "INV": "Inverness, Scotland - (INV)",
    "IYK": "Inyokern, CA, USA - (IYK)",
    "IOA": "Ioannina, Greece - (IOA)",
    "IPH": "Ipoh, Malaysia - (IPH)",
    "YFB": "Iqaluit, Nunavut, Canada - (YFB)",
    "IKT": "Irkutsk, Siberia, Russia - (IKT)",
    "IMT": "Iron Mountain, MI, USA - (IMT)",
    "IWD": "Ironwood, MI, USA - (IWD)",
    "ISB": "Islamabad-Rawalpindi, Pakistan - (ISB)",
    "ILY": "Islay Island, Scotland - (ILY)",
    "ISP": "Islip, NY, USA - (ISP)",
    "IST": "Istanbul, Turkey - (IST)",
    "SAW": "Istanbul, Turkey - (SAW)",
    "ITH": "Ithaca, NY, USA - (ITH)",
    "IVL": "Ivalo, Finland - (IVL)",
    "IWJ": "Iwami, Japan - (IWJ)",
    "ZIH": "Ixtapa, Mexico - (ZIH)",
    "ADB": "Izmir, Turkey - (ADB)",
    "IZO": "Izumo, Japan - (IZO)",
    "JAC": "Jackson Hole, WY, USA - (JAC)",
    "JAN": "Jackson, MS, USA - (JAN)",
    "MKL": "Jackson, TN, USA - (MKL)",
    "JAX": "Jacksonville, FL, USA - (JAX)",
    "OAJ": "Jacksonville, NC, USA - (OAJ)",
    "CGK": "Jakarta, Java, Indonesia - (CGK)",
    "JKT": "Jakarta, Java, Indonesia - (JKT)",
    "JAL": "Jalapa, Mexico - (JAL)",
    "JMS": "Jamestown, ND, USA - (JMS)",
    "JHW": "Jamestown, NY, USA - (JHW)",
    "JED": "Jeddah, Saudi Arabia - (JED)",
    "CJU": "Jeju, Korea, Republic of - (CJU)",
    "XRY": "Jerez de La Frontera, Spain - (XRY)",
    "JER": "Jersey, Channel Islands - (JER)",
    "JMU": "Jiamusi, China - (JMU)",
    "JIJ": "Jijiga, Ethiopia - (JIJ)",
    "JOE": "Joensuu, Finland - (JOE)",
    "JNB": "Johannesburg, South Africa - (JNB)",
    "JST": "Johnstown, PA, USA - (JST)",
    "JHB": "Johor Bahru, Malaysia - (JHB)",
    "JBR": "Jonesboro, AR, USA - (JBR)",
    "JKG": "Jonkoping, Sweden - (JKG)",
    "JLN": "Joplin, MO, USA - (JLN)",
    "JNU": "Juneau, AK, USA - (JNU)",
    "JYV": "Jyvaskyla, Finland - (JYV)",
    "KBL": "Kabul, Afghanistan - (KBL)",
    "KOJ": "Kagoshima, Japan - (KOJ)",
    "OGG": "Kahului, Maui, HI, USA - (OGG)",
    "KAT": "Kaitaia, New Zealand - (KAT)",
    "KAJ": "Kajaani, Finland - (KAJ)",
    "AZO": "Kalamazoo, MI, USA - (AZO)",
    "LUP": "Kalaupapa, Molokai, HI, USA - (LUP)",
    "KGI": "Kalgoorlie, W.A., Australia - (KGI)",
    "KLO": "Kalibo, Philippines - (KLO)",
    "KGD": "Kaliningrad, Russia - (KGD)",
    "FCA": "Kalispell, MT, USA - (FCA)",
    "KLR": "Kalmar, Sweden - (KLR)",
    "YKA": "Kamloops, BC, Canada - (YKA)",
    "KOA": "Kamuela, Hawaii, USA - (KOA)",
    "MCI": "Kansas City, MO, USA - (MCI)",
    "KHH": "Kaohsiung, Taiwan - (KHH)",
    "JHM": "Kapalua, Maui, HI, USA - (JHM)",
    "KHI": "Karachi, Pakistan - (KHI)",
    "KGF": "Karaganda, Kazakhstan - (KGF)",
    "KSD": "Karlstad, Sweden - (KSD)",
    "KTA": "Karratha, W.A., Australia - (KTA)",
    "KRP": "Karup, Denmark - (KRP)",
    "KHG": "Kashi, China - (KHG)",
    "KTM": "Kathmandu, Nepal - (KTM)",
    "KTW": "Katowice, Poland - (KTW)",
    "EAR": "Kearney, NE, USA - (EAR)",
    "YLW": "Kelowna, BC, Canada - (YLW)",
    "ENA": "Kenai, AK, USA - (ENA)",
    "YQK": "Kenora, ON, Canada - (YQK)",
    "KKE": "Kerikeri, New Zealand - (KKE)",
    "KTN": "Ketchikan, AK, USA - (KTN)",
    "EYW": "Key West, FL, USA - (EYW)",
    "HRK": "Kharkov, Ukraine - (HRK)",
    "KRT": "Khartoum, Sudan - (KRT)",
    "KKC": "Khon Kaen, Thailand - (KKC)",
    "KEL": "Kiel, Germany - (KEL)",
    "KBP": "Kiev, Ukraine - (KBP)",
    "KGL": "Kigali, Rwanda - (KGL)",
    "GRK": "Killeen, TX, USA - (GRK)",
    "AKN": "King Salmon, AK, USA - (AKN)",
    "IGM": "Kingman, AZ, USA - (IGM)",
    "KGC": "Kingscote, Kangaroo Island, S.A., Australia - (KGC)",
    "KIN": "Kingston, Jamaica - (KIN)",
    "KTP": "Kingston, Jamaica - (KTP)",
    "YGK": "Kingston, ON, Canada - (YGK)",
    "SVD": "Kingstown, St. Vincent - (SVD)",
    "FIH": "Kinshasa, Zaire - (FIH)",
    "IRK": "Kirksville, MO, USA - (IRK)",
    "KOI": "Kirkwall, Orkney Islands, Scotland - (KOI)",
    "KRN": "Kiruna, Sweden - (KRN)",
    "FKI": "Kisangani, Zaire - (FKI)",
    "KTT": "Kittila, Finland - (KTT)",
    "KLU": "Klagenfurt, Austria - (KLU)",
    "LMT": "Klamath Falls, OR, USA - (LMT)",
    "TYS": "Knoxville, TN, USA - (TYS)",
    "ADQ": "Kodiak, AK, USA - (ADQ)",
    "USM": "Koh Samui, Thailand - (USM)",
    "KOK": "Kokkola, Finland - (KOK)",
    "KMQ": "Komatsu, Japan - (KMQ)",
    "ROR": "Koror, Palau - (ROR)",
    "KGS": "Kos, Greece - (KGS)",
    "KSA": "Kosrae, Micronesia - (KSA)",
    "KBR": "Kota Bharu, Malaysia - (KBR)",
    "BKI": "Kota Kinabalu, Sabah, Malaysia - (BKI)",
    "KBV": "Krabi, Thailand - (KBV)",
    "KRK": "Krakow, Poland - (KRK)",
    "BON": "Kralendijk, Bonaire - (BON)",
    "KRF": "Kramfors, Sweden - (KRF)",
    "KRS": "Kristiansand, Norway - (KRS)",
    "KID": "Kristianstad, Sweden - (KID)",
    "KUL": "Kuala Lumpur, Malaysia - (KUL)",
    "TGG": "Kuala Terengganu, Malaysia - (TGG)",
    "KUA": "Kuantan, Malaysia - (KUA)",
    "KCH": "Kuching, Sarawak, Malaysia - (KCH)",
    "KMJ": "Kumamoto, Japan - (KMJ)",
    "KMG": "Kunming, China - (KMG)",
    "KUO": "Kuopio, Finland - (KUO)",
    "KUH": "Kushiro, Japan - (KUH)",
    "KWI": "Kuwait, Kuwait - (KWI)",
    "KZO": "Kzyl Orda, Kazakhstan - (KZO)",
    "LCG": "La Coruna, Spain - (LCG)",
    "LSE": "La Crosse, WI, USA - (LSE)",
    "LAP": "La Paz, Mexico - (LAP)",
    "LPB": "La Paz, Bolivia - (LPB)",
    "LRM": "La Romana, Dominican Republic - (LRM)",
    "LSC": "La Serena, Chile - (LSC)",
    "LFT": "Lafayette, LA, USA - (LFT)",
    "LOS": "Lagos, Nigeria - (LOS)",
    "LDU": "Lahad Datu, Sabah, Malaysia - (LDU)",
    "LHE": "Lahore, Pakistan - (LHE)",
    "LCH": "Lake Charles, LA, USA - (LCH)",
    "SUF": "Lamezia Terme, Italy - (SUF)",
    "LNY": "Lanai City, Lanai, HI, USA - (LNY)",
    "LNS": "Lancaster, PA, USA - (LNS)",
    "LGK": "Langkawi, Malaysia - (LGK)",
    "LAI": "Lannion, France - (LAI)",
    "LAN": "Lansing, MI, USA - (LAN)",
    "LHW": "Lanzhou, China - (LHW)",
    "LAR": "Laramie, WY, USA - (LAR)",
    "LRD": "Laredo, TX, USA - (LRD)",
    "LCA": "Larnaca, Cyprus - (LCA)",
    "LRU": "Las Cruces, NM, USA - (LRU)",
    "LPA": "Las Palmas, Grand Canary Island, Canary Islands - (LPA)",
    "LAS": "Las Vegas, NV, USA - (LAS)",
    "LBE": "Latrobe, PA, USA - (LBE)",
    "LST": "Launceston, Tas., Australia - (LST)",
    "PIB": "Laurel, MS, USA - (PIB)",
    "LAW": "Lawton, OK, USA - (LAW)",
    "LZC": "Lazaro Cardenas, Mexico - (LZC)",
    "LEH": "Le Havre, France - (LEH)",
    "LEB": "Lebanon, NH, USA - (LEB)",
    "LBA": "Leeds, England - (LBA)",
    "LGP": "Legaspi, Philippines - (LGP)",
    "LEJ": "Leipzig, Germany - (LEJ)",
    "BJX": "Leon, Mexico - (BJX)",
    "LEN": "Leon, Spain - (LEN)",
    "LSI": "Lerwick, Shetland Islands, Scotland - (LSI)",
    "YQL": "Lethbridge, AB, Canada - (YQL)",
    "LWS": "Lewiston, ID, USA - (LWS)",
    "LEX": "Lexington, KY, USA - (LEX)",
    "LXA": "Lhasa, Tibet, China - (LXA)",
    "LBL": "Liberal, KS, USA - (LBL)",
    "LIR": "Liberia, Costa Rica - (LIR)",
    "LBV": "Libreville, Gabon - (LBV)",
    "LIH": "Lihue, Kauai, HI, USA - (LIH)",
    "LJG": "Lijiang City, China - (LJG)",
    "LIL": "Lille, France - (LIL)",
    "LLW": "Lilongwe, Malawi - (LLW)",
    "LIM": "Lima, Peru - (LIM)",
    "LIG": "Limoges, France - (LIG)",
    "LNJ": "Lincang, China - (LNJ)",
    "LNK": "Lincoln, NE, USA - (LNK)",
    "LPI": "Linkoping, Sweden - (LPI)",
    "LNZ": "Linz, Austria - (LNZ)",
    "LIS": "Lisbon, Portugal - (LIS)",
    "LIT": "Little Rock, AR, USA - (LIT)",
    "LPL": "Liverpool, England - (LPL)",
    "LJU": "Ljubljana, Slovenia - (LJU)",
    "RJL": "Logrono, Spain - (RJL)",
    "LFW": "Lome, Togo - (LFW)",
    "LCY": "London, England - (LCY)",
    "LGW": "London, England - (LGW)",
    "LHR": "London, England - (LHR)",
    "LON": "London, England - (LON)",
    "STN": "London, England - (STN)",
    "YXU": "London, ON, Canada - (YXU)",
    "LDY": "Londonderry, Northern Ireland - (LDY)",
    "LBP": "Long Banga, Malaysia - (LBP)",
    "LGB": "Long Beach, CA, USA - (LGB)",
    "LRE": "Longreach, Qld., Australia - (LRE)",
    "GGG": "Longview, TX, USA - (GGG)",
    "LYR": "Longyearbyen, Svalbard, Norway - (LYR)",
    "LTO": "Loreto, Mexico - (LTO)",
    "LRT": "Lorient, France - (LRT)",
    "LAX": "Los Angeles, CA, USA - (LAX)",
    "SJD": "Los Cabos, Mexico - (SJD)",
    "SDF": "Louisville, KY, USA, USA - (SDF)",
    "LDE": "Lourdes, France - (LDE)",
    "LAD": "Luanda, Angola - (LAD)",
    "LBB": "Lubbock, TX, USA - (LBB)",
    "FBM": "Lubumbashi, Zaire - (FBM)",
    "LUG": "Lugano, Switzerland - (LUG)",
    "VSG": "Lugansk, Ukraine - (VSG)",
    "LUA": "Lukla, Nepal - (LUA)",
    "LLA": "Lulea, Sweden - (LLA)",
    "LUN": "Lusaka, Zambia - (LUN)",
    "LTN": "Luton, England - (LTN)",
    "LUX": "Luxembourg, Luxembourg - (LUX)",
    "LXR": "Luxor, Egypt - (LXR)",
    "LYC": "Lycksele, Sweden - (LYC)",
    "LYH": "Lynchburg, VA, USA - (LYH)",
    "LYS": "Lyon, France - (LYS)",
    "MKY": "Mackay, Qld., Australia - (MKY)",
    "MCN": "Macon, GA, USA - (MCN)",
    "MSN": "Madison, WI, USA - (MSN)",
    "MAD": "Madrid, Spain - (MAD)",
    "HGN": "Mae Hong Son, Thailand - (HGN)",
    "MRU": "Mahebourg, Mauritius - (MRU)",
    "MAJ": "Majuro, Marshall Islands - (MAJ)",
    "AAM": "Mala Mala, South Africa - (AAM)",
    "SSG": "Malabo, Bioko Island, Equatorial Guinea - (SSG)",
    "AGP": "Malaga, Spain - (AGP)",
    "MLE": "Male, Maldives - (MLE)",
    "MMA": "Malmo, Sweden - (MMA)",
    "MMX": "Malmo, Sweden - (MMX)",
    "MGA": "Managua, Nicaragua - (MGA)",
    "BAH": "Manama, Bahrain - (BAH)",
    "MAO": "Manaus, Brazil - (MAO)",
    "MAN": "Manchester, England - (MAN)",
    "MHT": "Manchester, NH, USA - (MHT)",
    "MAY": "Mangrove Cay, Andros Island, Bahamas - (MAY)",
    "MHK": "Manhattan, KS, USA - (MHK)",
    "MNL": "Manila, Philippines - (MNL)",
    "MBL": "Manistee, MI, USA - (MBL)",
    "ZLO": "Manzanillo, Mexico - (ZLO)",
    "MTS": "Manzini, Swaziland - (MTS)",
    "MAH": "Mao, Minorca, Spain - (MAH)",
    "MPM": "Maputo, Mozambique - (MPM)",
    "MAR": "Maracaibo, Venezuela - (MAR)",
    "MHQ": "Mariehamn, Aland, Finland - (MHQ)",
    "MII": "Marilia, Brazil - (MII)",
    "MWA": "Marion, IL, USA - (MWA)",
    "MPW": "Mariupol, Ukraine - (MPW)",
    "MCY": "Maroochydore, Qld., Australia - (MCY)",
    "MQT": "Marquette, MI, USA - (MQT)",
    "RAK": "Marrakech, Morocco - (RAK)",
    "MRS": "Marseille, France - (MRS)",
    "MHH": "Marsh Harbour, Abaco Island, Bahamas - (MHH)",
    "MVY": "Martha's Vineyard, MA, USA - (MVY)",
    "MSU": "Maseru, Lesotho - (MSU)",
    "MCW": "Mason City, IA, USA - (MCW)",
    "MSS": "Massena, NY, USA - (MSS)",
    "MFK": "Matsu, Taiwan - (MFK)",
    "MYJ": "Matsuyama, Japan - (MYJ)",
    "MZT": "Mazatlan, Mexico - (MZT)",
    "MFE": "McAllen, TX, USA - (MFE)",
    "MCK": "McCook, NE, USA - (MCK)",
    "MES": "Medan, Sumatra, Indonesia - (MES)",
    "MDE": "Medellin, Colombia - (MDE)",
    "MFR": "Medford, OR, USA - (MFR)",
    "YXH": "Medicine Hat, AB, Canada - (YXH)",
    "MLB": "Melbourne, FL, USA - (MLB)",
    "AVV": "Melbourne, Vic., Australia - (AVV)",
    "MEL": "Melbourne, Vic., Australia - (MEL)",
    "MLN": "Melilla, Spain - (MLN)",
    "MMB": "Memanbetsu, Japan - (MMB)",
    "MEM": "Memphis, TN, USA - (MEM)",
    "MDZ": "Mendoza, Argentina - (MDZ)",
    "MID": "Merida, Mexico - (MID)",
    "MEI": "Meridian, MS, USA - (MEI)",
    "MIM": "Merimbula, N.S.W., Australia - (MIM)",
    "ETZ": "Metz, France - (ETZ)",
    "MXL": "Mexicali, Mexico - (MXL)",
    "MEX": "Mexico City, Mexico - (MEX)",
    "MIA": "Miami, FL, USA - (MIA)",
    "MIG": "Mian Yang, China - (MIG)",
    "MAF": "Midland, TX, USA - (MAF)",
    "JMK": "Mikonos, Greece - (JMK)",
    "LIN": "Milan, Italy - (LIN)",
    "MIL": "Milan, Italy - (MIL)",
    "MXP": "Milan, Italy - (MXP)",
    "MQL": "Mildura, Vic., Australia - (MQL)",
    "MLS": "Miles City, MT, USA - (MLS)",
    "MKE": "Milwaukee, WI, USA - (MKE)",
    "MSP": "Minneapolis, MN, USA - (MSP)",
    "MOT": "Minot, ND, USA - (MOT)",
    "MHP": "Minsk, Belarus - (MHP)",
    "MSQ": "Minsk, Belarus - (MSQ)",
    "MYY": "Miri, Sarawak, Malaysia - (MYY)",
    "MSJ": "Misawa, Japan - (MSJ)",
    "MSO": "Missoula, MT, USA - (MSO)",
    "KMI": "Miyazaki, Japan - (KMI)",
    "MOB": "Mobile, AL, USA - (MOB)",
    "MOD": "Modesto, CA, USA - (MOD)",
    "MGQ": "Mogadishu, Somalia - (MGQ)",
    "MLI": "Moline, IL, USA - (MLI)",
    "MBA": "Mombasa, Kenya - (MBA)",
    "MIR": "Monastir, Tunisia - (MIR)",
    "LOV": "Monclova, Mexico - (LOV)",
    "YQM": "Moncton, NB, Canada - (YQM)",
    "MLU": "Monroe, LA, USA - (MLU)",
    "ROB": "Monrovia, Liberia - (ROB)",
    "YYY": "Mont-Joli, PQ, Canada - (YYY)",
    "MBJ": "Montego Bay, Jamaica - (MBJ)",
    "MRY": "Monterey, CA, USA - (MRY)",
    "MTY": "Monterrey, Mexico - (MTY)",
    "MVD": "Montevideo, Uruguay - (MVD)",
    "MGM": "Montgomery, AL, USA - (MGM)",
    "MPL": "Montpellier, France - (MPL)",
    "YMQ": "Montreal, PQ, Canada - (YMQ)",
    "YUL": "Montreal, PQ, Canada - (YUL)",
    "MTJ": "Montrose, CO, USA - (MTJ)",
    "MXX": "Mora, Sweden - (MXX)",
    "MRZ": "Moree, N.S.W., Australia - (MRZ)",
    "MLM": "Morelia, Mexico - (MLM)",
    "MGW": "Morgantown, WV, USA - (MGW)",
    "HAH": "Moroni, Comoro Islands - (HAH)",
    "MYA": "Moruya, N.S.W., Australia - (MYA)",
    "MOW": "Moscow, Russia - (MOW)",
    "SVO": "Moscow, Russia - (SVO)",
    "VKO": "Moscow, Russia - (VKO)",
    "MGB": "Mount Gambier, S.A., Australia - (MGB)",
    "ISA": "Mount Isa, Qld., Australia - (ISA)",
    "MDG": "Mudanjiang, China - (MDG)",
    "MLH": "Mulhouse, France - (MLH)",
    "MZV": "Mulu, Malaysia - (MZV)",
    "BOM": "Mumbai (Bombay), India - (BOM)",
    "MUC": "Munich, Germany - (MUC)",
    "FMO": "Munster, Germany - (FMO)",
    "MJV": "Murcia, Spain - (MJV)",
    "MMK": "Murmansk, Russia - (MMK)",
    "MCT": "Muscat, Oman - (MCT)",
    "MSL": "Muscle Shoals, AL, USA - (MSL)",
    "MKG": "Muskegon, MI, USA - (MKG)",
    "MYR": "Myrtle Beach, SC, USA - (MYR)",
    "MJT": "Mytilene, Lesbos Island, Greece - (MJT)",
    "NDJ": "N'Djamena, Chad - (NDJ)",
    "NAN": "Nadi, Fiji - (NAN)",
    "NDR": "Nador, Morocco - (NDR)",
    "NGS": "Nagasaki, Japan - (NGS)",
    "NGO": "Nagoya, Japan - (NGO)",
    "NKM": "Nagoya, Japan - (NKM)",
    "OKA": "Naha, Okinawa, Japan - (OKA)",
    "NBO": "Nairobi, Kenya - (NBO)",
    "NST": "Nakhon Si Thammarat, Thailand - (NST)",
    "YCD": "Nanaimo, BC, Canada - (YCD)",
    "KHN": "Nanchang, China - (KHN)",
    "LZN": "Nangen, Taiwan - (LZN)",
    "NKG": "Nanjing, China - (NKG)",
    "SHM": "Nanki Shirahama, Japan - (SHM)",
    "NNG": "Nanning, China - (NNG)",
    "NTE": "Nantes, France - (NTE)",
    "ACK": "Nantucket, MA, USA - (ACK)",
    "NPE": "Napier, New Zealand - (NPE)",
    "NAP": "Naples, Italy - (NAP)",
    "APF": "Naples, FL, USA - (APF)",
    "NAA": "Narrabri, N.S.W., Australia - (NAA)",
    "NRA": "Narrandera, N.S.W., Australia - (NRA)",
    "NVK": "Narvik, Norway - (NVK)",
    "NNM": "Naryan Mar, Russia - (NNM)",
    "BNA": "Nashville, TN, USA - (BNA)",
    "NAS": "Nassau, Bahamas - (NAS)",
    "PID": "Nassau, Bahamas - (PID)",
    "ASJ": "Naze, Amami-O Island, Japan - (ASJ)",
    "NSN": "Nelson, New Zealand - (NSN)",
    "MQP": "Nelspruit, South Africa - (MQP)",
    "EWN": "New Bern, NC, USA - (EWN)",
    "HVN": "New Haven, CT, USA - (HVN)",
    "MSY": "New Orleans, LA, USA - (MSY)",
    "JFK": "New York, NY, USA - (JFK)",
    "LGA": "New York, NY, USA - (LGA)",
    "NYC": "New York, NY, USA - All Airports (NYC)",
    "EWR": "New York/Newark, NJ, USA - (EWR)",
    "SWF": "Newburgh, NY, USA - (SWF)",
    "NCL": "Newcastle, England - (NCL)",
    "NTL": "Newcastle, N.S.W., Australia - (NTL)",
    "ZNE": "Newman, W.A., Australia - (ZNE)",
    "PHF": "Newport News, VA, USA - (PHF)",
    "NIM": "Niamey, Niger - (NIM)",
    "NCE": "Nice, France - (NCE)",
    "KIJ": "Niigata, Japan - (KIJ)",
    "NGB": "Ningbo, China - (NGB)",
    "GOJ": "Nizhniy Novgorod, Russia - (GOJ)",
    "OME": "Nome, AK, USA - (OME)",
    "ORF": "Norfolk, VA, USA - (ORF)",
    "NRK": "Norrkoping, Sweden - (NRK)",
    "YYB": "North Bay, ON, Canada - (YYB)",
    "OTH": "North Bend, OR, USA - (OTH)",
    "ELH": "North Eleuthera, Bahamas - (ELH)",
    "LBF": "North Platte, NE, USA - (LBF)",
    "NWI": "Norwich, England - (NWI)",
    "NKC": "Nouakchott, Mauritania - (NKC)",
    "GEA": "Noumea, New Caledonia - (GEA)",
    "NOU": "Noumea, New Caledonia - (NOU)",
    "OVB": "Novosibirsk, Siberia, Russia - (OVB)",
    "NLD": "Nuevo Laredo, Mexico - (NLD)",
    "NUE": "Nuremberg, Germany - (NUE)",
    "OAK": "Oakland, CA, USA - (OAK)",
    "OAX": "Oaxaca, Mexico - (OAX)",
    "OBO": "Obihiro, Japan - (OBO)",
    "OCJ": "Ocho Rios, Jamaica - (OCJ)",
    "ONJ": "Odate Noshiro, Japan - (ONJ)",
    "ODS": "Odessa, Ukraine - (ODS)",
    "OGS": "Ogdensburg, NY, USA - (OGS)",
    "OIT": "Oita, Japan - (OIT)",
    "OKC": "Oklahoma City, OK, USA - (OKC)",
    "OLB": "Olbia, Sardinia, Italy - (OLB)",
    "OLP": "Olympic Dam, S.A., Australia - (OLP)",
    "OMA": "Omaha, NE, USA - (OMA)",
    "OMS": "Omsk, Siberia, Russia - (OMS)",
    "ONT": "Ontario, CA, USA - (ONT)",
    "SNA": "Orange County, CA, USA - (SNA)",
    "OAG": "Orange, N.S.W., Australia - (OAG)",
    "AUA": "Oranjestad, Aruba - (AUA)",
    "EUX": "Oranjestad, St. Eustatius - (EUX)",
    "ORB": "Orebro, Sweden - (ORB)",
    "MCO": "Orlando, FL, USA - (MCO)",
    "OER": "Ornskoldsvik, Sweden - (OER)",
    "ITM": "Osaka, Japan - (ITM)",
    "KIX": "Osaka, Japan - (KIX)",
    "OSA": "Osaka, Japan - (OSA)",
    "OSL": "Oslo, Norway - (OSL)",
    "ZOS": "Osorno, Chile - (ZOS)",
    "OSD": "Ostersund, Sweden - (OSD)",
    "OSR": "Ostrava, Czech Republic - (OSR)",
    "YOW": "Ottawa, ON, Canada - (YOW)",
    "OUA": "Ouagadougou, Burkina Faso - (OUA)",
    "OUL": "Oulu, Finland - (OUL)",
    "OWB": "Owensboro, KY, USA - (OWB)",
    "PAD": "Paderborn, Germany - (PAD)",
    "PAH": "Paducah, KY, USA - (PAH)",
    "PGA": "Page, AZ, USA - (PGA)",
    "PPG": "Pago Pago, Tutuila, American Samoa - (PPG)",
    "PJA": "Pajala, Sweden - (PJA)",
    "PLM": "Palembang, Sumatra, Indonesia - (PLM)",
    "PMO": "Palermo, Sicily, Italy - (PMO)",
    "PSP": "Palm Springs, CA, USA - (PSP)",
    "PMI": "Palma, Mallorca, Spain - (PMI)",
    "PMW": "Palmas, Brazil - (PMW)",
    "PMR": "Palmerston North, New Zealand - (PMR)",
    "PNA": "Pamplona, Spain - (PNA)",
    "PTY": "Panama City, Panama - (PTY)",
    "PFN": "Panama City, FL, USA - (PFN)",
    "PPT": "Papeete, Tahiti, French Polynesia - (PPT)",
    "PFO": "Paphos, Cyprus - (PFO)",
    "PBO": "Paraburdoo, W.A., Australia - (PBO)",
    "PBM": "Paramaribo, Suriname - (PBM)",
    "CDG": "Paris, France - (CDG)",
    "ORY": "Paris, France - (ORY)",
    "PAR": "Paris, France - (PAR)",
    "PKB": "Parkersburg, WV, USA - (PKB)",
    "PKE": "Parkes, N.S.W., Australia - (PKE)",
    "PSC": "Pasco, WA, USA - (PSC)",
    "PUF": "Pau, France - (PUF)",
    "PLN": "Pellston, MI, USA - (PLN)",
    "PEN": "Penang, Penang Island, Malaysia - (PEN)",
    "PDT": "Pendleton, OR, USA - (PDT)",
    "PNS": "Pensacola, FL, USA - (PNS)",
    "YYF": "Penticton, BC, Canada - (YYF)",
    "PIA": "Peoria, IL, USA - (PIA)",
    "PGF": "Perpignan, France - (PGF)",
    "PER": "Perth, W.A., Australia - (PER)",
    "PEG": "Perugia, Italy - (PEG)",
    "PEW": "Peshawar, Pakistan - (PEW)",
    "PKC": "Petropavlovsk-Kamchatsky, Siberia, Russia - (PKC)",
    "PHL": "Philadelphia, PA, USA - (PHL)",
    "SXM": "Philipsburg, St. Maarten - (SXM)",
    "PHS": "Phitsanulok, Thailand - (PHS)",
    "PNH": "Phnom Penh, Cambodia - (PNH)",
    "PHX": "Phoenix, AZ, USA - (PHX)",
    "HKT": "Phuket, Thailand - (HKT)",
    "PDS": "Piedras Negras, Mexico - (PDS)",
    "PIR": "Pierre, SD, USA - (PIR)",
    "PSA": "Pisa, Italy - (PSA)",
    "PIT": "Pittsburgh, PA, USA - (PIT)",
    "PLJ": "Placencia, Belize - (PLJ)",
    "PXU": "Pleiku, Vietnam - (PXU)",
    "PIH": "Pocatello, ID, USA - (PIH)",
    "PNI": "Pohnpei, Micronesia - (PNI)",
    "PTP": "Pointe-A-Pitre, Grande-Terre, Guadeloupe - (PTP)",
    "PDL": "Ponta Delgada, Sao Miguel Island, Azores - (PDL)",
    "YZT": "Port Hardy, BC, Canada - (YZT)",
    "PHE": "Port Hedland, W.A., Australia - (PHE)",
    "PLO": "Port Lincoln, S.A., Australia - (PLO)",
    "PQQ": "Port Macquarie, N.S.W., Australia - (PQQ)",
    "POM": "Port Moresby, Papua-New Guinea - (POM)",
    "POS": "Port of Spain, Trinidad and Tobago - (POS)",
    "VLI": "Port Vila, Efate Island, Vanuatu - (VLI)",
    "PAP": "Port-au-Prince, Haiti - (PAP)",
    "PWM": "Portland, ME, USA - (PWM)",
    "PDX": "Portland, OR, USA - (PDX)",
    "PTJ": "Portland, Vic., Australia - (PTJ)",
    "OPO": "Porto, Portugal - (OPO)",
    "POA": "Porto Alegre, Brazil - (POA)",
    "PXO": "Porto Santo, Madeira - (PXO)",
    "PSM": "Portsmouth, NH, USA - (PSM)",
    "YPW": "Powell River, BC, Canada - (YPW)",
    "POZ": "Poznan, Poland - (POZ)",
    "PRG": "Prague, Czech Republic - (PRG)",
    "PRC": "Prescott, AZ, USA - (PRC)",
    "PQI": "Presque Isle, ME, USA - (PQI)",
    "YXS": "Prince George, BC, Canada - (YXS)",
    "YPR": "Prince Rupert, BC, Canada - (YPR)",
    "PPP": "Proserpine, Qld., Australia - (PPP)",
    "PVD": "Providence, RI, USA - (PVD)",
    "PLS": "Providenciales Island, Turks and Caicos Islands - (PLS)",
    "PVC": "Provincetown, MA, USA - (PVC)",
    "ZPC": "Pucon, Chile - (ZPC)",
    "PBC": "Puebla, Mexico - (PBC)",
    "PUB": "Pueblo, CO, USA - (PUB)",
    "FUE": "Puerto del Rosario, Fuerteventura Island, Canary Islands - (FUE)",
    "PXM": "Puerto Escondido, Mexico - (PXM)",
    "PMC": "Puerto Montt, Chile - (PMC)",
    "POP": "Puerto Plata, Dominican Republic - (POP)",
    "PPS": "Puerto Princesa, Philippines - (PPS)",
    "PVR": "Puerto Vallarta, Mexico - (PVR)",
    "PUW": "Pullman, WA, USA - (PUW)",
    "PUQ": "Punta Arenas, Tierra del Fuego, Chile - (PUQ)",
    "PUJ": "Punta Cana, Dominican Republic - (PUJ)",
    "PND": "Punta Gorda, Belize - (PND)",
    "FNJ": "Pyongyang, North Korea - (FNJ)",
    "TAO": "Qingdao, China - (TAO)",
    "YQB": "Quebec, PQ, Canada - (YQB)",
    "ZQN": "Queenstown, New Zealand - (ZQN)",
    "QRO": "Queretaro, Mexico - (QRO)",
    "YQZ": "Quesnel, BC, Canada - (YQZ)",
    "UIP": "Quimper, France - (UIP)",
    "UIN": "Quincy, IL, USA - (UIN)",
    "UIO": "Quito, Ecuador - (UIO)",
    "VKG": "Rach Gia, Vietnam - (VKG)",
    "RDU": "Raleigh, NC, USA - (RDU)",
    "RGN": "Rangoon, Myanmar (Burma) - (RGN)",
    "YRT": "Rankin Inlet, NWT, Canada - (YRT)",
    "UNN": "Ranong, Thailand - (UNN)",
    "RAP": "Rapid City, SD, USA - (RAP)",
    "REC": "Recife, Brazil - (REC)",
    "YRL": "Red Lake, ON, Canada - (YRL)",
    "RDD": "Redding, CA, USA - (RDD)",
    "RDM": "Redmond, OR, USA - (RDM)",
    "REG": "Reggio di Calabria, Italy - (REG)",
    "YQR": "Regina, SK, Canada - (YQR)",
    "RNS": "Rennes, France - (RNS)",
    "RNO": "Reno, NV, USA - (RNO)",
    "KEF": "Reykjavik, Iceland - (KEF)",
    "REK": "Reykjavik, Iceland - (REK)",
    "RKV": "Reykjavik, Iceland - (RKV)",
    "REX": "Reynosa, Mexico - (REX)",
    "RHI": "Rhinelander, WI, USA - (RHI)",
    "RHO": "Rhodes, Greece - (RHO)",
    "RIC": "Richmond, VA, USA - (RIC)",
    "RIX": "Riga, Latvia - (RIX)",
    "RMI": "Rimini, Italy - (RMI)",
    "GIG": "Rio de Janeiro, Brazil - (GIG)",
    "RIO": "Rio de Janeiro, Brazil - (RIO)",
    "SDU": "Rio de Janeiro, Brazil - (SDU)",
    "RIW": "Riverton, WY, USA - (RIW)",
    "RUH": "Riyadh, Saudi Arabia - (RUH)",
    "ROA": "Roanoke, VA, USA - (ROA)",
    "RST": "Rochester, MN, USA - (RST)",
    "ROC": "Rochester, NY, USA - (ROC)",
    "RSD": "Rock Sound, Bahamas - (RSD)",
    "RKS": "Rock Springs, WY, USA - (RKS)",
    "RFD": "Rockford, IL, USA - (RFD)",
    "ROK": "Rockhampton, Qld., Australia - (ROK)",
    "RKD": "Rockland, ME, USA - (RKD)",
    "RDZ": "Rodez, France - (RDZ)",
    "RMA": "Roma, Qld., Australia - (RMA)",
    "CIA": "Rome, Italy - (CIA)",
    "FCO": "Rome, Italy (FCO-Leonardo Da Vinci - (FCO)",
    "ROM": "Rome, Italy - (ROM)",
    "RNN": "Ronne, Denmark - (RNN)",
    "RNB": "Ronneby, Sweden - (RNB)",
    "DOM": "Roseau, Dominica - (DOM)",
    "ROV": "Rostov, Russia - (ROV)",
    "ROW": "Roswell, NM, USA - (ROW)",
    "ROT": "Rotorua, New Zealand - (ROT)",
    "RTM": "Rotterdam, Netherlands - (RTM)",
    "URO": "Rouen, France - (URO)",
    "YUY": "Rouyn-Noranda, PQ, Canada - (YUY)",
    "RVN": "Rovaniemi, Finland - (RVN)",
    "RXS": "Roxas City, Philippines - (RXS)",
    "RUT": "Rutland, VT, USA - (RUT)",
    "RZE": "Rzeszow, Poland - (RZE)",
    "SAB": "Saba Island, Saba - (SAB)",
    "SMF": "Sacramento, CA, USA - (SMF)",
    "HSG": "Saga, Japan - (HSG)",
    "MBS": "Saginaw, MI, USA - (MBS)",
    "YSJ": "Saint John, NB, Canada - (YSJ)",
    "RUN": "Saint-Denis, Reunion - (RUN)",
    "ZSE": "Saint-Pierre, Reunion - (ZSE)",
    "SPN": "Saipan, Northern Mariana Islands - (SPN)",
    "SLN": "Salina, KS, USA - (SLN)",
    "SBY": "Salisbury, MD, USA - (SBY)",
    "SLC": "Salt Lake City, UT, USA - (SLC)",
    "SLW": "Saltillo, Mexico - (SLW)",
    "SSA": "Salvador, Brazil - (SSA)",
    "SZG": "Salzburg, Austria - (SZG)",
    "SZF": "Samsun, Turkey - (SZF)",
    "ADZ": "San Andres, Colombia - (ADZ)",
    "SAQ": "San Andros, Bahamas - (SAQ)",
    "SJT": "San Angelo, TX, USA - (SJT)",
    "SAT": "San Antonio, TX, USA - (SAT)",
    "BRC": "San Carlos de Bariloche, Argentina - (BRC)",
    "SAN": "San Diego, CA, USA - (SAN)",
    "SFO": "San Francisco, CA, USA - (SFO)",
    "SJO": "San Jose, Costa Rica - (SJO)",
    "SJC": "San Jose, CA, USA - (SJC)",
    "SJU": "San Juan, Puerto Rico - (SJU)",
    "SBP": "San Luis Obispo, CA, USA - (SBP)",
    "SLP": "San Luis Potosi, Mexico - (SLP)",
    "SAL": "San Salvador, El Salvador - (SAL)",
    "EAS": "San Sebastian, Spain - (EAS)",
    "SAH": "Sanaa, Yemen - (SAH)",
    "SDP": "Sand Point, AK, USA - (SDP)",
    "SDK": "Sandakan, Sabah, Malaysia - (SDK)",
    "TRF": "Sandefjord, Norway - (TRF)",
    "YZP": "Sandspit, Queen Charlotte Islands, BC, Canada - (YZP)",
    "SBA": "Santa Barbara, CA, USA - (SBA)",
    "SPC": "Santa Cruz, Spain - (SPC)",
    "TCI": "Santa Cruz de Tenerife, Canary Islands - (TFN)",
    "SAF": "Santa Fe, NM, USA - (SAF)",
    "SMX": "Santa Maria, CA, USA - (SMX)",
    "SID": "Santa Maria, Sal Island, Cape Verde - (SID)",
    "RSA": "Santa Rosa, Argentina - (RSA)",
    "STS": "Santa Rosa, CA, USA - (STS)",
    "SDR": "Santander, Spain - (SDR)",
    "SCL": "Santiago, Chile - (SCL)",
    "STI": "Santiago, Dominican Republic - (STI)",
    "SDQ": "Santo Domingo, Dominican Republic - (SDQ)",
    "SYX": "Sanya, China - (SYX)",
    "SJP": "Sao Jose So Rio Preto, Brazil - (SJP)",
    "CGH": "Sao Paulo, Brazil - (CGH)",
    "GRU": "Sao Paulo, Brazil - (GRU)",
    "SAO": "Sao Paulo, Brazil - (SAO)",
    "CTS": "Sapporo, Japan - (CTS)",
    "OKD": "Sapporo, Japan - (OKD)",
    "SJJ": "Sarajevo, Bosnia and Herzegovina - (SJJ)",
    "SLK": "Saranac Lake, NY, USA - (SLK)",
    "SRQ": "Sarasota, FL, USA - (SRQ)",
    "YXE": "Saskatoon, SK, Canada - (YXE)",
    "CIU": "Sault Ste. Marie, MI, USA - (CIU)",
    "YAM": "Sault Ste. Marie, ON, Canada - (YAM)",
    "SAV": "Savannah, GA, USA - (SAV)",
    "BFF": "Scottsbluff, NE, USA - (BFF)",
    "SEA": "Seattle, WA, USA - (SEA)",
    "PLX": "Semipalatinsk, Kazakhstan - (PLX)",
    "GMP": "Seoul, Korea, Republic of - (GMP)",
    "ICN": "Seoul, Korea, Republic of - (ICN)",
    "YZV": "Sept-Iles, PQ, Canada - (YZV)",
    "SVQ": "Seville, Spain - (SVQ)",
    "PVG": "Shanghai, China - (PVG)",
    "SHA": "Shanghai, China - (SHA)",
    "SNN": "Shannon, Ireland - (SNN)",
    "SWA": "Shantou, China - (SWA)",
    "SHJ": "Sharjah, United Arab Emirates - (SHJ)",
    "SSH": "Sharm El Sheikh, Egypt - (SSH)",
    "SHD": "Shenandoah Valley Airport, VA, USA - (SHD)",
    "SHE": "Shenyang, China - (SHE)",
    "SZX": "Shenzhen, China - (SZX)",
    "SHR": "Sheridan, WY, USA - (SHR)",
    "SJW": "Shijiazhuang, China - (SJW)",
    "SHV": "Shreveport, LA, USA - (SHV)",
    "SBW": "Sibu, Sarawak, Malaysia - (SBW)",
    "SDY": "Sidney, MT, USA - (SDY)",
    "SVC": "Silver City, NM, USA - (SVC)",
    "SIN": "Singapore, Singapore - (SIN)",
    "SUX": "Sioux City, IA, USA - (SUX)",
    "FSD": "Sioux Falls, SD, USA - (FSD)",
    "YXL": "Sioux Lookout, ON, Canada - (YXL)",
    "SIT": "Sitka, AK, USA - (SIT)",
    "SGY": "Skagway, AK, USA - (SGY)",
    "SFT": "Skelleftea, Sweden - (SFT)",
    "SKP": "Skopje, Macedonia - (SKP)",
    "YYD": "Smithers, BC, Canada - (YYD)",
    "SOF": "Sofia, Bulgaria - (SOF)",
    "SGD": "Sonderborg, Denmark - (SGD)",
    "JZH": "Songpan Jiuzhai Huanglong, China - (JZH)",
    "SBN": "South Bend, IN, USA - (SBN)",
    "SOU": "Southampton, England - (SOU)",
    "SPU": "Split, Croatia - (SPU)",
    "GEG": "Spokane, WA, USA - (GEG)",
    "SPI": "Springfield, IL, USA - (SPI)",
    "SGF": "Springfield, MO, USA - (SGF)",
    "VSF": "Springfield, VT, USA - (VSF)",
    "STC": "St. Cloud, MN, USA - (STC)",
    "SGU": "St. George, UT, USA - (SGU)",
    "GND": "St. George's, Grenada - (GND)",
    "ANU": "St. John's, Antigua - (ANU)",
    "YYT": "St. John's, NF, Canada - (YYT)",
    "STL": "St. Louis, MO, USA - (STL)",
    "LED": "St. Petersburg, Russia - (LED)",
    "PIE": "St. Petersburg, FL, USA - (PIE)",
    "SCE": "State College, PA, USA - (SCE)",
    "SVG": "Stavanger, Norway - (SVG)",
    "SML": "Stella Maris, Long Island, Bahamas - (SML)",
    "ARN": "Stockholm, Sweden - (ARN)",
    "BMA": "Stockholm, Sweden - (BMA)",
    "STO": "Stockholm, Sweden - (STO)",
    "SYY": "Stornoway, Isle of Lewis, Scotland - (SYY)",
    "SXB": "Strasbourg, France - (SXB)",
    "STR": "Stuttgart, Germany - (STR)",
    "SFS": "Subic Bay, Philippines - (SFS)",
    "YSB": "Sudbury, ON, Canada - (YSB)",
    "THS": "Sukhothai, Thailand - (THS)",
    "SUN": "Sun Valley, ID, USA - (SUN)",
    "SDL": "Sundsvall, Sweden - (SDL)",
    "SUB": "Surabaya, Java, Indonesia - (SUB)",
    "URT": "Surat Thani, Thailand - (URT)",
    "SUV": "Suva, Fiji - (SUV)",
    "YQY": "Sydney, Cape Breton Island, NS, Canada - (YQY)",
    "SYD": "Sydney, N.S.W., Australia - (SYD)",
    "SYR": "Syracuse, NY, USA - (SYR)",
    "SZZ": "Szczecin, Poland - (SZZ)",
    "TCP": "Taba, Egypt - (TCP)",
    "TBZ": "Tabriz, Iran - (TBZ)",
    "TAC": "Tacloban, Philippines - (TAC)",
    "TAE": "Taegu, South Korea - (TAE)",
    "TAG": "Tagbilaran, Philippines - (TAG)",
    "RMQ": "Taichung, Taiwan - (RMQ)",
    "TPE": "Taipei, Taiwan - (TPE)",
    "TSA": "Taipei, Taiwan - (TSA)",
    "TYN": "Taiyuan, China - (TYN)",
    "TAK": "Takamatsu, Japan - (TAK)",
    "TLH": "Tallahassee, FL, USA - (TLH)",
    "TLL": "Tallinn, Estonia - (TLL)",
    "TPA": "Tampa, FL, USA - (TPA)",
    "TMP": "Tampere, Finland - (TMP)",
    "TAM": "Tampico, Mexico - (TAM)",
    "TMW": "Tamworth, N.S.W., Australia - (TMW)",
    "TNG": "Tangier, Morocco - (TNG)",
    "TAP": "Tapachula, Mexico - (TAP)",
    "TAS": "Tashkent, Uzbekistan - (TAS)",
    "TUO": "Taupo, New Zealand - (TUO)",
    "TRG": "Tauranga, New Zealand - (TRG)",
    "TWU": "Tawau, Sabah, Malaysia - (TWU)",
    "TBS": "Tbilisi, Georgia - (TBS)",
    "MME": "Teesside, England - (MME)",
    "TGU": "Tegucigalpa, Honduras - (TGU)",
    "THR": "Tehran, Iran - (THR)",
    "TLV": "Tel Aviv, Israel - (TLV)",
    "TEX": "Telluride, CO, USA - (TEX)",
    "ZCO": "Temuco, Chile - (ZCO)",
    "TFS": "Tenerife Island, South, Canary Islands - (TFS)",
    "TFN": "Tenerife Island, North, Canary Islands - (TFN)",
    "TPQ": "Tepic, Mexico - (TPQ)",
    "TMJ": "Termez, Uzbekistan - (TMJ)",
    "YXT": "Terrace, BC, Canada - (YXT)",
    "TXK": "Texarkana, AR, USA - (TXK)",
    "AXA": "The Valley, Anguilla - (AXA)",
    "SKG": "Thessaloniki, Greece - (SKG)",
    "TVF": "Thief River Falls, MN, USA - (TVF)",
    "JTR": "Thira, Santorini Island, Greece - (JTR)",
    "YTH": "Thompson, MB, Canada - (YTH)",
    "YQT": "Thunder Bay, ON, Canada - (YQT)",
    "TSN": "Tianjin, China - (TSN)",
    "TIJ": "Tijuana, Mexico - (TIJ)",
    "TIU": "Timaru, New Zealand - (TIU)",
    "YTS": "Timmins, ON, Canada - (YTS)",
    "TIA": "Tirana, Albania - (TIA)",
    "TAB": "Tobago, Trinidad and Tobago - (TAB)",
    "OOK": "Toksook Bay, AK, USA - (OOK)",
    "HND": "Tokyo, Japan - (HND)",
    "NRT": "Tokyo, Japan - (NRT)",
    "TYO": "Tokyo, Japan - (TYO)",
    "TOL": "Toledo, OH, USA - (TOL)",
    "TLC": "Toluca, Mexico - (TLC)",
    "TEN": "Tongren, China - (TEN)",
    "YTO": "Toronto, ON, Canada - (YTO)",
    "YTZ": "Toronto, ON, Canada - (YTZ)",
    "YYZ": "Toronto, ON, Canada - (YYZ)",
    "TRC": "Torreon, Mexico - (TRC)",
    "TLN": "Toulon, France - (TLN)",
    "TLS": "Toulouse, France - (TLS)",
    "TSV": "Townsville, Qld., Australia - (TSV)",
    "TST": "Trang, Thailand - (TST)",
    "TDX": "Trat, Thailand - (TDX)",
    "TVC": "Traverse City, MI, USA - (TVC)",
    "TCB": "Treasure Cay, Abaco Island, Bahamas - (TCB)",
    "TTN": "Trenton, NJ, USA - (TTN)",
    "TRI": "Tri-City Airport, TN, USA - (TRI)",
    "TRS": "Trieste, Italy - (TRS)",
    "TIP": "Tripoli, Libya - (TIP)",
    "TOS": "Tromso, Norway - (TOS)",
    "TRD": "Trondheim, Norway - (TRD)",
    "TKK": "Truk, Micronesia - (TKK)",
    "TUS": "Tucson, AZ, USA - (TUS)",
    "TUL": "Tulsa, OK, USA - (TUL)",
    "TUN": "Tunis, Tunisia - (TUN)",
    "TUP": "Tupelo, MS, USA - (TUP)",
    "TRN": "Turin, Italy - (TRN)",
    "TKU": "Turku, Finland - (TKU)",
    "TGZ": "Tuxtla Gutierrez, Mexico - (TGZ)",
    "TWF": "Twin Falls, ID, USA - (TWF)",
    "TYR": "Tyler, TX, USA - (TYR)",
    "UBP": "Ubon Ratchathani, Thailand - (UBP)",
    "UTH": "Udon Thani, Thailand - (UTH)",
    "UPG": "Ujung Pandang, Sulawesi, Indonesia - (UPG)",
    "ULN": "Ulan Bator, Mongolia - (ULN)",
    "UME": "Umea, Sweden - (UME)",
    "UNA": "Una, Brazil - (UNA)",
    "UNK": "Unalakleet, AK, USA - (UNK)",
    "URC": "Urumqi, Sinkiang, China - (URC)",
    "USH": "Ushuaia, Tierra del Fuego, Argentina - (USH)",
    "UKK": "Ust Kamenogorsk, Kazakhstan - (UKK)",
    "UTP": "Utapao, Thailand - (UTP)",
    "VAA": "Vaasa, Finland - (VAA)",
    "EGE": "Vail, CO, USA - (EGE)",
    "YVO": "Val-d'Or, PQ, Canada - (YVO)",
    "VDZ": "Valdez, AK, USA - (VDZ)",
    "ZAL": "Valdivia, Chile - (ZAL)",
    "VLD": "Valdosta, GA, USA - (VLD)",
    "VLC": "Valencia, Spain - (VLC)",
    "VLL": "Valladolid, Spain - (VLL)",
    "MLA": "Valletta, Malta - (MLA)",
    "YVR": "Vancouver, BC, Canada - (YVR)",
    "VNS": "Varanasi, India - (VNS)",
    "VAR": "Varna, Bulgaria - (VAR)",
    "VST": "Vasteras, Sweden - (VST)",
    "VXO": "Vaxjo, Sweden - (VXO)",
    "VCE": "Venice, Italy - (VCE)",
    "VER": "Veracruz, Mexico - (VER)",
    "VRN": "Verona, Italy - (VRN)",
    "YYJ": "Victoria, BC, Canada - (YYJ)",
    "SEZ": "Victoria, Mahe Island, Seychelles - (SEZ)",
    "VCT": "Victoria, TX, USA - (VCT)",
    "VIE": "Vienna, Austria - (VIE)",
    "VTE": "Vientiane, Laos - (VTE)",
    "VQS": "Vieques, Puerto Rico - (VQS)",
    "UVF": "Vieux Fort, St. Lucia - (UVF)",
    "VGO": "Vigo, Spain - (VGO)",
    "VHM": "Vilhelmina, Sweden - (VHM)",
    "VSA": "Villahermosa, Mexico - (VSA)",
    "VNO": "Vilnius, Lithuania - (VNO)",
    "VII": "Vinh City, Vietnam - (VII)",
    "VIS": "Visalia, CA, USA - (VIS)",
    "VBY": "Visby, Sweden - (VBY)",
    "VIT": "Vitoria, Spain - (VIT)",
    "VVO": "Vladivostok, Siberia, Russia - (VVO)",
    "VOG": "Volgograd, Russia - (VOG)",
    "YWK": "Wabush, Labrador, NF, Canada - (YWK)",
    "ACT": "Waco, TX, USA - (ACT)",
    "WGA": "Wagga-Wagga, N.S.W., Australia - (WGA)",
    "NTQ": "Wajima, Japan - (NTQ)",
    "ALW": "Walla Walla, WA, USA - (ALW)",
    "WAG": "Wanganui, New Zealand - (WAG)",
    "QRW": "Warri, Nigeria - (QRW)",
    "WAW": "Warsaw, Poland - (WAW)",
    "DCA": "Washington DC, USA - (DCA)",
    "IAD": "Washington DC, USA - (IAD)",
    "WAS": "Washington DC, USA - (WAS)",
    "ALO": "Waterloo, IA, USA - (ALO)",
    "ART": "Watertown, NY, USA - (ART)",
    "ATY": "Watertown, SD, USA - (ATY)",
    "CWA": "Wausau, WI, USA - (CWA)",
    "WEI": "Weipa, Qld., Australia - (WEI)",
    "WLG": "Wellington, New Zealand - (WLG)",
    "EAT": "Wenatchee, WA, USA - (EAT)",
    "PBI": "West Palm Beach, FL, USA - (PBI)",
    "WYS": "West Yellowstone, MT, USA - (WYS)",
    "WSZ": "Westport, New Zealand - (WSZ)",
    "WHK": "Whakatane, New Zealand - (WHK)",
    "WRE": "Whangarei, New Zealand - (WRE)",
    "HPN": "White Plains, NY, USA - (HPN)",
    "YXY": "Whitehorse, YT, Canada - (YXY)",
    "WYA": "Whyalla, S.A., Australia - (WYA)",
    "SPS": "Wichita Falls, TX, USA - (SPS)",
    "ICT": "Wichita, KS, USA - (ICT)",
    "WIC": "Wick, Scotland - (WIC)",
    "AVP": "Wilkes-Barre, PA, USA - (AVP)",
    "CUR": "Willemstad, Curacao - (CUR)",
    "YWL": "Williams Lake, BC, Canada - (YWL)",
    "IPT": "Williamsport, PA, USA - (IPT)",
    "ISN": "Williston, ND, USA - (ISN)",
    "ILG": "Wilmington, DE, USA - (ILG)",
    "ILM": "Wilmington, NC, USA - (ILM)",
    "YQG": "Windsor, ON, Canada - (YQG)",
    "YWG": "Winnipeg, MB, Canada - (YWG)",
    "OLF": "Wolf Point, MT, USA - (OLF)",
    "WRL": "Worland, WY, USA - (WRL)",
    "WRG": "Wrangell, AK, USA - (WRG)",
    "WRO": "Wroclaw, Poland - (WRO)",
    "WUH": "Wuhan, China - (WUH)",
    "XIY": "Xi'an, China - (XIY)",
    "XMN": "Xiamen, China - (XMN)",
    "XIC": "Xichang, China - (XIC)",
    "YKM": "Yakima, WA, USA - (YKM)",
    "YAK": "Yakutat, AK, USA - (YAK)",
    "GAJ": "Yamagata, Japan - (GAJ)",
    "YNY": "Yangyang, Korea, Republic of - (YNY)",
    "YNJ": "Yanji, China - (YNJ)",
    "YNT": "Yantai, China - (YNT)",
    "NSI": "Yaounde, Cameroon - (NSI)",
    "YAO": "Yaounde, Cameroon - (YAO)",
    "YAP": "Yap, Micronesia - (YAP)",
    "YZF": "Yellowknife, NWT, Canada - (YZF)",
    "EVN": "Yerevan, Armenia - (EVN)",
    "JOG": "Yogyakarta, Java, Indonesia - (JOG)",
    "YUM": "Yuma, AZ, USA - (YUM)",
    "ZCL": "Zacatecas, Mexico - (ZCL)",
    "ZAD": "Zadar, Croatia - (ZAD)",
    "ZAG": "Zagreb, Croatia - (ZAG)",
    "ZAM": "Zamboanga, Philippines - (ZAM)",
    "ZNZ": "Zanzibar, Tanzania - (ZNZ)",
    "ZAZ": "Zaragoza, Spain - (ZAZ)",
    "CGO": "Zhengzhou, China - (CGO)",
    "HSN": "Zhoushan, China - (HSN)",
    "ZRH": "Zurich, Switzerland - (ZRH)",
    "???": "Surprise Me"
}
