quote_dictionary = {
    "1": '“To my mind, the greatest reward and luxury of travel is to be able to experience everyday things as if for the first time, to be in a position in which almost nothing is so familiar it is taken for granted.” – Bill Bryson',
    "2": '“The world is a book and those who do not travel read only one page.” – St. Augustine',
    "3": '“Travel is never a matter of money, but of courage.” – Paulo Coelho',
    "4": '“With age, comes wisdom. With travel, comes understanding.” – Sandra Lake',
    "5": '“When overseas you learn more about your own country, than you do the place you’re visiting.” – Clint Borgen',
    "6": '“Travel is fatal to prejudice, bigotry, and narrow-mindedness.” – Mark Twain',
    "7": '“Don’t tell me the sky’s the limit when there are footprints on the moon.” – Paul Brandt',
    "8": '“The man who goes alone can start today; but he who travels with another must wait till that other is ready.” – Henry David Thoreau',
    "9": '“The first condition of understanding a foreign country is to smell it.” – Rudyard Kipling',
    "10": '“A journey of a thousand miles must begin with a single step.” – Lao Tzu',
    "11": '“When preparing to travel, lay out all your clothes and all your money. Then take half the clothes and twice the money.” – Susan Heller Anderson',
    "12": '“No place is ever as bad as they tell you it’s going to be.” – Chuck Thompson',
    "13": '“We live in a wonderful world that is full of beauty, charm and adventure. There is no end to the adventures we can have if only we seek them with our eyes open.” – Jawaharlal Nehru',
    "14": '“A good traveler has no fixed plans and is not intent on arriving.” – Lao Tzu',
    "15": '“There is no moment of delight in any pilgrimage like the beginning of it.” – Charles Dudley Warner',
    "16": '“A ship in harbor is safe, but that’s not what ships were built for.” – John A. Shedd',
    "17": '“Tourists don’t know where they’ve been, travelers don’t know where they’re going.” – Paul Theroux',
    "18": '“Not all those who wander are lost.” – J. R. R. Tolkien',
    "19": '“Do not follow where the path may lead. Go instead where there is no path and leave a trail.” – Ralph Waldo Emerson',
    "20": '“Like all great travelers, I have seen more than I remember, and remember more than I have seen.” – Benjamin Disraeli',
    "21": '“Once a year, go somewhere you’ve never been before.” – The Dalai Lama',
    "22": '“No one realizes how beautiful it is to travel until he comes home and rests his head on his old, familiar pillow.” – Lin Yutang',
    "23": '“What you’ve done becomes the judge of what you’re going to do – especially in other people’s minds. When you’re traveling, you are what you are right there and then. People don’t have your past to hold against you. No yesterdays on the road.” – William Least Heat Moon',
    "24": '“There are no foreign lands. It is the traveler only who is foreign.” – Robert Louis Stevenson',
    "25": '“Travel is glamorous only in retrospect.” – Paul Theroux',
    "26": '“A traveler without observation is a bird without wings.” – Moslih Eddin Saadi',
    "27": '“Your true traveler finds boredom rather agreeable than painful. It is the symbol of his liberty-his excessive freedom. He accepts his boredom, when it comes, not merely philosophically, but almost with pleasure.” – Aldous Huxley',
    "28": '“One’s destination is never a place, but a new way of seeing things.” – Henry Miller',
    "29": '“All travel has its advantages. If the passenger visits better countries, he may learn to improve his own. And if fortune carries him to worse, he may learn to enjoy it.” – Samuel Johnson',
    "30": '“Wandering re-establishes the original harmony which once existed between man and the universe.” – Anatole France',
    "31": '“I can’t control the wind but I can adjust the sail.” – Ricky Skaggs',
    "32": '“We wander for distraction, but we travel for fulfilment.” – Hilaire Belloc',
    "33": '“People travel to faraway places to watch, in fascination, the kind of people they ignore at home.” – Dagobert D. Runes',
    "34": '“If you reject the food, ignore the customs, fear the religion and avoid the people, you might better stay at home.” – James Michener',
    "35": '“The use of traveling is to regulate imagination by reality, and instead of thinking how things may be, to see them as they are.” – Samuel Johnson',
    "36": '“You don’t have to be rich to travel well.” – Eugene Fodor',
    "37": '“Perhaps travel cannot prevent bigotry, but by demonstrating that all peoples cry, laugh, eat, worry, and die, it can introduce the idea that if we try and understand each other, we may even become friends.” – Maya Angelou',
    "38": '“All journeys have secret destinations of which the traveler is unaware.” – Martin Buber',
    "39": '“Two roads diverged in a wood and I – I took the one less traveled by.” – Robert Frost',
    "40": '“Travel and change of place impart new vigor to the mind.” – Seneca',
    "41": '“Traveling is a brutality. It forces you to trust strangers and to lose sight of all that familiar comfort of home and friends. You are constantly off balance. Nothing is yours except the essential things – air, sleep, dreams, the sea, the sky – all things tending towards the eternal or what we imagine of it.” – Cesare Pavese',
    "42": '“Once the travel bug bites, there is no known antidote, and I know that I shall be happily infected until the end of my life.” ― Michael Palin',
    "43": '“A journey is best measured in friends, rather than miles.” – Tim Cahill',
    "44": '“A journey is like marriage. The certain way to be wrong is to think you control it.” – John Steinbeck',
    "45": '“When you travel, remember that a foreign country is not designed to make you comfortable. It is designed to make its own people comfortable.” – Clifton Fadiman',
    "46": '“There are far, far better things ahead than we leave behind.” – C.S. Lewis',
    "47": '“Travel does what good novelists also do to the life of everyday, placing it like a picture in a frame or a gem in its setting, so that the intrinsic qualities are made more clear. Travel does this with the very stuff that everyday life is made of, giving to it the sharp contour and meaning of art.” – Freya Stark',
    "48": '“To travel is to discover that everyone is wrong about other countries.” – Aldous Huxley',
    "49": '“All the pathos and irony of leaving one’s youth behind is thus implicit in every joyous moment of travel: one knows that the first joy can never be recovered, and the wise traveler learns not to repeat successes but tries new places all the time.” – Paul Fussell',
    "50": '“I have found out that there ain’t no surer way to find out whether you like people or hate them than to travel with them.” – Mark Twain',
    "51": '“The whole object of travel is not to set foot on foreign land; it is at last to set foot on one’s own country as a foreign land.” – G.K. Chesterton',
    "52": '“Too often travel, instead of broadening the mind, merely lengthens the conversation.” – Elizabeth Drew',
    "53": '“People don’t take trips, trips take people.” – John Steinbeck',
    "54": '“Stuff your eyes with wonder, live as if you’d drop dead in ten seconds. See the world. It’s more fantastic than any dream made or paid for in factories.” – Ray Bradbury',
    "55": '“Travel makes one modest. You see what a tiny place you occupy in the world.” – Gustave Flaubert',
    "56": '“The journey not the arrival matters.” – T. S. Eliot',
    "57": '“Time flies. It’s up to you to be the navigator.” – Robert Orben',
    "58": '“The real voyage of discovery consists not in seeking new landscapes, but in having new eyes.” – Marcel Proust',
    "59": '“I never travel without my diary. One should always have something sensational to read in the train.” – Oscar Wilde',
    "60": '“For my part, I travel not to go anywhere, but to go. I travel for travel’s sake. The great affair is to move.” – Robert Louis Stevenson',
    "61": '“If an ass goes travelling, he’ll not come home a horse.” – Thomas Fuller',
    "62": '“Travelling tends to magnify all human emotions.” – Peter Hoeg',
    "63": '“To move, to breathe, to fly, to float, To gain all while you give, To roam the roads of lands remote: To travel is to live.” – Hans Christian Andersen',
    "64": '“To awaken quite alone in a strange town is one of the pleasantest sensations in the world.” – Freya Stark',
    "65": '“I am not the same having seen the moon shine from the other side of the world.” – Mary Anne Radmacher',
    "66": '“I always wonder why birds stay in the same place when they can fly anywhere on earth. Then I ask myself the same question.” – Harun Yahya',
    "67": '“I dislike feeling at home when I am abroad.” – George Bernard Shaw',
    "68": '“A wise traveler never despises his own country.” – Carlo Goldoni',
    "69": '“Man cannot discover new oceans unless he has the courage to lose sight of the shore.” – Andre Gide',
    "70": '“Traveling – it leaves you speechless, then turns you into a storyteller.” – Ibn Battuta',
    "71": '“We travel, some of us forever, to seek other places, other lives, other souls.” – Anais Nin',
    "72": '“Travel is more than the seeing of sights; it is a change that goes on, deep and permanent, in the ideas of living.” – Miriam Beard',
    "73": '“The gladdest moment in human life, methinks, is a departure into unknown lands.” – Richard Burton',
    "74": '“A man of ordinary talent will always be ordinary, whether he travels or not; but a man of superior talent will go to pieces if he remains forever in the same place.” – Wolfgang Amadeus Mozart',
    "75": '“He who would travel happily must travel light.” – Antoine de St. Exupery',
    "76": '“Our battered suitcases were piled on the sidewalk again; we had longer ways to go. But no matter, the road is life.” – Jack Kerouac',
    "77": '“Twenty years from now you will be more disappointed by the things you didn’t do than by the ones you did do. So throw off the bowlines, sail away from the safe harbor. Catch the trade winds in your sails. Explore. Dream. Discover.” – Mark Twain'
}
